name: Android CI

on:
  push:
    branches: [ main, Develop ]
  pull_request:
    branches: [ main, Develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Generate Jacoco Report
        run: ./gradlew jacocoTestReport

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: app/build/test-results/testDebugUnitTest/

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: app/build/reports/jacoco/jacocoTestReport/

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=Hyuga974_GameMixAndroid
            -Dsonar.organization=Hyuga
            -Dsonar.sources=app/src/main
            -Dsonar.tests=app/src/test,app/src/androidTest
            -Dsonar.java.binaries=app/build
            -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

